version: '3.8'
services:
  # Backend Service
  backend:
    build:
      context: ./knowledge-kiosk-server
    ports:
      - 5001:5000
    environment:
      - DB_URL=mongodb://mongo:27017 # Reference to DB_URL from .env file
      - JWT_SECRET=${JWT_SECRET}  # Reference to JWT_SECRET from .env file
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=localhost,127.0.0.1
    volumes:
      - ./knowledge-kiosk-server:/app
    depends_on:
      - mongo  
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # MongoDB root user
      MONGO_INITDB_ROOT_PASSWORD: password123  # MongoDB root password
      MONGO_INITDB_DATABASE: knowledge-kiosk  # MongoDB database
    volumes:
      - ./data/db:/data/db  # Persist MongoDB data between restarts
